# Generated by Django 4.1 on 2022-09-19 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("django_taxi", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="termtaxonomyitem",
            name="object_id",
            field=models.TextField(),
        ),
    ]
